// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyqvhowqdcndaczchqhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5cXZob3dxZGNuZGFjemNocWhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwMTM5MDIsImV4cCI6MjA1NTU4OTkwMn0.IEtwTIBfIRYJVVYd8ekp12d2rR6v9_lEqkISKSpn2J0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);